### PR TITLE
lt_LT | 65% done

### PR DESCRIPTION
**Pull request by TheOnlyGhostwolf**
### Description of Your Pull Request
What does your pull request specifically does by adding/modifying or removing code?
Pengubot will be able to speak in new language - Lithuanian
### Changes Proposed and or Files Changed
- Example Change
New file: lt_LT.js
### Label Your Pull Request
- [ ] This PR modifies existing code to enhance the bot
- [ ] This PR fixes a bug within the bot
- [ ] This PR removes/renames methods or properties
- [x] This PR adds methods, features, commands or properties

Note: Translated 65% of all strings.

### CODE REVIEW

**Comment by MrJacz** [comment]
@TheOnlyGhostwolf any update on this?

**Comment by TheOnlyGhostwolf** [comment]
Sorry, I was pretty busy recently. I'm now waiting for spring holiday (in a few weeks or so) so I could continue to translate everything.

**Comment by MrJacz** [comment]
Alright

**Comment by MrJacz** [comment]
We will be switching a new platform to do translations in the future. We're also completely rewriting most of the strings. I'm going to close this PR because of these reasons.

**Pull request closed without merging**
